### ISSUE TITLE
Git for versioning of docs

### ISSUE THREAD

**Issue by pekkah** [pekkah/tanka-docs-gen#36]
Git should be used as source of generating multiple versions of docs.

Extend configuration with
```yaml

sources:
  branches:
  - master
  tags:
  - 1.*
  - 2.*
```

Generate

1. Clone/checkout each branch and tag to cache folder
2. Locate tanka-docs.yml/yaml from each folder
3. run generate docs overriding the output path to point to a branch/tag specific folder
4. Generate indexing site
